### PR TITLE
Add openWEMI commonWork example diagrams

### PR DESCRIPTION
**Pull request by seanpetiya**
Includes diagram.io file

### CODE REVIEW

**Review by kcoyle — CHANGES_REQUESTED** [review]
Sean, it would be best to show this without any openwemi entities - just the "commonWork" ones. Thanks.

**Comment by seanpetiya** [comment]
Updated diagrams per feedback, removed openwemi references.

**Comment by seanpetiya** [comment]
The commonWork diagram has been updated per feedback, and now includes entities from LOC, Amazon, Wikidata, and YouTube connected through the `openwemi:commonWork` property to a MusicBrainz entity. The diagram is attached below for reference, and the original draw.io files are included for future editing.

commonwork-diagram-v2

**Comment by seanpetiya** [comment]
The diagram has been updated per feedback from the meeting on 11/29:

commonwork-letitbe-v2

**Pull request merged**
